In [18]:
# ===== Importar as bibliotecas ===== #

import pandas as pd
import numpy as np
import locale
import plotly.graph_objects as go
import plotly.express as px
import sqlalchemy as sa
from datetime import date

# Definir as propriedades de datas em Português BR
locale.setlocale(locale.LC_TIME, 'pt_BR')

# Função para formatar valores numéricos em Moeda Brasileira R$
def formatar_moeda(valor):
    locale.setlocale(locale.LC_ALL, 'pt_BR.utf8')
    valor_formatado = locale.currency(valor, grouping=True, symbol='R$')
    return valor_formatado

# Função para formatar valores números em quantidades com 1 casa decimal
def formatar_quantidade(valor):
    return '{:,.2f}'.format(valor).replace(',', 'temp').replace('.', ',').replace('temp', '.')

# Função para formatar valores numéricos em percentual
def formatar_percentual(valor):
    return '{:,.0f}%'.format(valor)

# Função para formatar datas no padrão brasileiro com dia, mes e ano - d/m/a
def formatar_data(data):
    return data.strftime('%d/%m/%Y')

# Função para formatar o cpf no padrão brasileiro 000.000.000.00
def formatar_cpf(numero):
    numero_str = str(numero).zfill(11)  # Preenche com zeros à esquerda se necessário
    cpf_formatado = f'{numero_str[:3]}.{numero_str[3:6]}.{numero_str[6:9]}-{numero_str[9:]}'
    return cpf_formatado

# ===== Carregar o token do Mapbox para geração do Gráfio de Mapa ===== #
mapbox_token = 'pk.eyJ1IjoiYmVua2VmYSIsImEiOiJjbGRmemt5NjUwaXRlM3ZzMnRvbmV1NDRrIn0.OJ2myrAkytpmthW9QG4mig'

# ===== Conexão Local ===== #
engine = sa.create_engine('mysql+mysqldb://root:root@localhost/harpia_animais')

# ===== Criar os dataframes ===== #
def dados(engine, data_ini=None, data_fin=None, pessoa=None):
    query = 'SELECT * FROM ocorrencia'
    params = []
    
    #if data_ini and data_fin:
    #    query += ' WHERE dataocorrencia BETWEEN %s AND %s'
    #    params.extend([data_ini, data_fin])
    #elif data_ini:
    #    query += ' WHERE dataocorrencia >= %s'
    #    params.append(data_ini)
    #elif data_fin:
    #    query += ' WHERE dataocorrencia <= %s'
    #    params.append(data_fin)
    #
    #if pessoa:
    #    if 'WHERE' in query:
    #        query += ' AND nome_cli = %s'
    #    else:
    #        query += ' WHERE nome_cli = %s'
    #    params.append(pessoa)

    ocorrencia = pd.read_sql_query(query, engine, params=params)
    #codigo_ocorrencia_map = dict(zip(ocorrencia['nomeocorrencia'], ocorrencia['idocorrencia']))
    
    cidade = pd.read_sql_query('SELECT * from cidade', engine)
    codigo_cidade_map = dict(zip(cidade['nomecidade'], cidade['idcidade']))
    
    bairro = pd.read_sql_query('SELECT * from bairro', engine)
    codigo_bairro_map = dict(zip(bairro['nomebairro'], bairro['idbairro']))
    
    gruposituacao = pd.read_sql_query('SELECT * from gruposituacao', engine)
    codigo_gruposituacao_map = dict(zip(gruposituacao['nomegruposituacao'], gruposituacao['idgruposituacao']))
    
    situacaoanimal = pd.read_sql_query('SELECT * from situacaoanimal', engine)
    situacaoanimal = pd.merge(situacaoanimal, gruposituacao[['idgruposituacao', 'nomegruposituacao']], on = 'idgruposituacao', how='left')
    codigo_situacao_map = dict(zip(situacaoanimal['nomesituacaoanimal'], situacaoanimal['idsituacaoanimal']))


    grupoanimal = pd.read_sql_query('SELECT * from grupoanimal', engine)
    codigo_grupoanimal_map = dict(zip(grupoanimal['nomegrupoanimal'], grupoanimal['idgrupoanimal']))

    racaanimal = pd.read_sql_query('SELECT * from racaanimal', engine)
    racaanimal = pd.merge(racaanimal, grupoanimal[['idgrupoanimal', 'nomegrupoanimal']], on = 'idgrupoanimal', how='left')
    codigo_raca_animal_map = dict(zip(racaanimal['nomeracaanimal'], racaanimal['idracaanimal']))
    
    situacao = {'situacao': [0,1],
                'nomesituacao': ['Aberto', 'Finalizado']}
    situacao = pd.DataFrame(situacao)
    
    ocorrencia = pd.merge(ocorrencia, situacao[['situacao', 'nomesituacao']], on = 'situacao', how='left')
    
    ocorrencia = pd.merge(ocorrencia, cidade[['idcidade', 'nomecidade']], on = 'idcidade', how='left')
    ocorrencia = pd.merge(ocorrencia, bairro[['idbairro', 'nomebairro', 'latitude', 'longitude']], on = 'idbairro', how='left')
    ocorrencia = pd.merge(ocorrencia, situacaoanimal[['idsituacaoanimal', 'nomesituacaoanimal']], on = 'idsituacaoanimal', how='left')
    ocorrencia = pd.merge(ocorrencia, racaanimal[['idracaanimal', 'nomeracaanimal', 'nomegrupoanimal']], on = 'idracaanimal', how='left')
    
    ocorrencia['dataocorrencia']= pd.to_datetime(ocorrencia['dataocorrencia'], dayfirst=True)
    ocorrencia['dataresolucao']= pd.to_datetime(ocorrencia['dataresolucao'], dayfirst=True)
    
    ocorrencia['latitude'] = ocorrencia['latitude'].str.replace(',', '.').astype(float)
    ocorrencia['longitude'] = ocorrencia['longitude'].str.replace(',', '.').astype(float)


    ocorrencia['mesocorrencia'] = ocorrencia['dataocorrencia'].dt.strftime('%B')
    ocorrencia['messolucao'] = ocorrencia['dataresolucao'].dt.strftime('%B')

    mesocorrencia = {'codmes_ocorrencia':[1,2,3,4,5,6,7,8,9,10,11,12],
         'mesocorrencia':['janeiro', 'fevereiro', 'março', 'abril', 'maio', 'junho', 'julho', 'agosto', 'setembro', 'outubro', 'novembro', 'dezembro']}
    mesocorrencia = pd.DataFrame(mesocorrencia) 
    
    mesresolucao = {'codmes_solucao':[1,2,3,4,5,6,7,8,9,10,11,12],
         'messolucao':['janeiro', 'fevereiro', 'março', 'abril', 'maio', 'junho', 'julho', 'agosto', 'setembro', 'outubro', 'novembro', 'dezembro']}
    mesresolucao = pd.DataFrame(mesresolucao) 
    
    ocorrencia = pd.merge(ocorrencia, mesocorrencia, on = 'mesocorrencia', how='left')
    ocorrencia = pd.merge(ocorrencia, mesresolucao, on = 'messolucao', how='left')
    
    

    #ocorrencia['dataocorrencia_formatado'] = ocorrencia['dataocorrencia']
    #ocorrencia['dataresolucao_formatado'] = ocorrencia['dataresolucao']
    #for campo in ['dataocorrencia_formatado', 'dataresolucao_formatado']:
    #    ocorrencia[campo]=ocorrencia[campo].map(formatar_data)
    
    ocorrencia['nome_ocorrencia_completo'] = ocorrencia.apply(lambda row: f"{row['idocorrencia']} - {row['dataocorrencia']} - {row['nomerua']} - {row['nomebairro']} - {row['nomegrupoanimal']}", axis=1)
    codigo_ocorrencia_map=dict(zip(ocorrencia['nome_ocorrencia_completo'], ocorrencia['idocorrencia']))
    
    #colunas_organizadas = ['nome_ocorrencia_completo']
    
    #ocorrencia = ocorrencia.reindex(columns=colunas_organizadas)
    
       
    return ocorrencia, cidade, codigo_cidade_map, bairro, codigo_bairro_map, gruposituacao, codigo_gruposituacao_map, situacaoanimal, codigo_situacao_map, grupoanimal, codigo_grupoanimal_map, racaanimal, codigo_raca_animal_map
ocorrencia, cidade, codigo_cidade_map, bairro, codigo_bairro_map, gruposituacao, codigo_gruposituacao_map, situacaoanimal, codigo_situacao_map, grupoanimal, codigo_grupoanimal_map, racaanimal, codigo_raca_animal_map = dados(engine)

In [19]:
ocorrencia_filtrado = ocorrencia
ocorrencia_filtrado.head(1)

,idocorrencia,idracaanimal,idsituacaoanimal,dataocorrencia,dataresolucao,situacao,idcidade,idbairro,nomerua,observacao,...,latitude,longitude,nomesituacaoanimal,nomeracaanimal,nomegrupoanimal,mesocorrencia,messolucao,codmes_ocorrencia,codmes_solucao,nome_ocorrencia_completo
0,1,1,1,2024-09-29,2024-12-24,1,1,1,Avenida Nereu Ramos,teste 01,...,-29.111614,-49.644336,Machucado,Golden,Cachorros,setembro,dezembro,9,12.0,1 - 2024-09-29 00:00:00 - Avenida Nereu Ramos ...

In [20]:
ocorrencia_filtrado.dtypes

idocorrencia                         int64
idracaanimal                         int64
idsituacaoanimal                     int64
dataocorrencia              datetime64[ns]
dataresolucao               datetime64[ns]
situacao                             int64
idcidade                             int64
idbairro                             int64
nomerua                             object
observacao                          object
idgrupoanimal                        int64
solucao                             object
nomesituacao                        object
nomecidade                          object
nomebairro                          object
latitude                           float64
longitude                          float64
nomesituacaoanimal                  object
nomeracaanimal                      object
nomegrupoanimal                     object
mesocorrencia                       object
messolucao                          object
codmes_ocorrencia                    int64
codmes_solucao                     float64
nome_ocorrencia_completo            object
dtype: object

In [29]:
# Lançamento de Ocorrência - Cadastrar nova ocorrencia - Tela de ocorrencias
@app.callback(
    [Output('mensagem_ocorrencia_salvo_01', 'children'),
     Output('data_lancamento_ocorrencia_01', 'date'),
     Output('dropdown_nomebairro_lancamento_ocorrencia_01', 'value'),
     Output('rua_lancamento_ocorrencia_01', 'value'),
     Output('dropdown_nomegrupoanimal_lancamento_ocorrencia_01', 'value'),
     Output('dropdown_nomeracaanimal_lancamento_ocorrencia_01', 'value'),
     Output('dropdown_nomesituacaoanimal_lancamento_ocorrencia_01', 'value'),
     Output('observacao_lancamento_ocorrencia_01', 'value')],
    Input('botao_salvar_lancamento_ocorrencia_01', 'n_clicks'),
    [State('data_lancamento_ocorrencia_01', 'date'),
     State('dropdown_nomebairro_lancamento_ocorrencia_01', 'value'),
     State('rua_lancamento_ocorrencia_01', 'value'),
     State('dropdown_nomegrupoanimal_lancamento_ocorrencia_01', 'value'),
     State('dropdown_nomeracaanimal_lancamento_ocorrencia_01', 'value'),
     State('dropdown_nomesituacaoanimal_lancamento_ocorrencia_01', 'value'),
     State('observacao_lancamento_ocorrencia_01', 'value')]
)
def salvar_ocorrencia(n_clicks, dataocorrencia, idbairro, nomerua, idgrupoanimal, idracaanimal, idsituacaoanimal, observacao):
    atualizar_dados_globais()
    if n_clicks is not None and dataocorrencia is not None and idbairro is not None and idgrupoanimal is not None and idracaanimal is not None and idsituacaoanimal is not None and observacao is not None:
        try:  
            idbairro = codigo_bairro_map[idbairro]
            idgrupoanimal = codigo_grupoanimal_map[idgrupoanimal]
            idracaanimal = codigo_raca_animal_map[idracaanimal]
            idsituacaoanimal = codigo_situacao_map[idsituacaoanimal]

            nova_ocorrencia = {'idbairro': idbairro, 'nomerua': nomerua, 'idgrupoanimal': idgrupoanimal, 'idracaanimal': idracaanimal, 
                               'idsituacaoanimal': idsituacaoanimal, 'dataocorrencia': dataocorrencia, 'observacao': observacao}         

            with engine.connect() as conn:
                conn.execute(sa.text("INSERT INTO ocorrencia (idbairro, nomerua, idgrupoanimal, idracaanimal, idsituacaoanimal, dataocorrencia, observacao) VALUES (:idbairro, :nomerua, :idgrupoanimal, :idracaanimal, :idsituacaoanimal, :dataocorrencia, :observacao)"), nova_ocorrencia)
                conn.commit()
                    
            return ('Ocorrência registrada com sucesso!', None, None, '', None, None, None, '')
    
        except Exception as e:
            return (f'Erro ao salvar cadastro de ocorrência! Verifique se todos os campos estão preenchidos e tente novamente.! {str(e)}', None, None, '', None, None, None, '')
        
    return ('Erro ao salvar cadastro de ocorrência! Verifique se todos os campos estão preenchidos e tente novamente.', None, None, '', None, None, None, '')

,Código,Situação do Animal,Data,Situação,Data Resolução,Observação,Solução
18,35,2126,12/12/2024,Aberto,NaT,sfzdklcsdiuhf siudh goisdfh sdfhgfnvlknbkvn fh...,None
17,34,Machucado,01/01/2025,Finalizado,06/01/2025,,None
16,32,Cinomose,27/12/2024,Finalizado,31/12/2024,Cachorro avistado com sinais de cinomose.,Cachorro recolhido.
15,31,Machucado,31/12/2024,Aberto,NaT,311224-0917,None
14,30,Machucado,03/12/2024,Aberto,NaT,,None
13,29,Machucado,28/12/2024,Aberto,NaT,,None
12,28,Machucado,29/12/2024,Aberto,NaT,,None
11,27,Machucado,18/12/2024,Finalizado,29/12/2024,dffafafasdfs,teste
10,26,Asa quebrada,22/12/2024,Finalizado,25/12/2024,Teste de observação.,sfdfadf
9,25,Machucado,24/10/2024,Aberto,NaT,Cachorro machucado.,None
8,24,Machucado,03/10/2024,Aberto,NaT,"Cachorro mancando, sem ferimentos abertos apar...",None
7,23,Machucado,25/09/2024,Aberto,NaT,Wvajagwksuwgswo,None
6,22,Machucado,17/09/2024,Finalizado,07/01/2025,czvdsfvdvfasd,Animal retirado e encaminhado para tratamento ...
5,21,Machucado,25/09/2024,Finalizado,29/12/2024,fvffsgsf,dfsfs
4,20,Machucado,25/09/2024,Finalizado,29/12/2024,zvzxvzcxvzxvzcv,dfsdfs
3,19,Machucado,27/09/2024,Finalizado,29/12/2024,czcxcsafsdf,None
2,18,Machucado,09/10/2024,Finalizado,18/12/2024,dfaffadsf,None
1,16,Machucado,29/09/2024,Finalizado,30/10/2024,Outro teste,None
0,1,Machucado,29/09/2024,Finalizado,24/12/2024,teste 01,lucas